name: update website

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - name: Initialisation
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Setup environment
      run: pip install -r requirements.txt

    - name: build website
      run: make html

    - name: link check
      run: make linkcheck
      continue-on-error: true  # check for broken links but do not fail job, an error is still displayed in the job output

    - name: upload pages artifacts
      uses: actions/upload-pages-artifact@v3
      with:
        path: build/html/

  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}

    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}

    runs-on: ubuntu-latest

    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

